const centersWidgets = [
  {
    id: 1,
    label: "Total No. of Imaging Centers",
    counter: "197",
    // badge: "ri-arrow-up-line",
    // badgeClass: "success",
    // percentage: "17.32 %",
    // icon: "ri-ticket-2-line",
    // iconClass: "info",
    // decimals: 1,
    // prefix: "",
    // suffix: "k",
  },
  {
    id: 2,
    label: "In-Progress",
    counter: "30",
    // badge: "ri-arrow-down-line",
    // badgeClass: "danger",
    // percentage: "0.87 %",
    // icon: "mdi mdi-timer-sand",
    // iconClass: "warning",
    // decimals: 1,
    // prefix: "",
    // suffix: "k",
  },
  {
    id: 3,
    label: "Pending",
    counter: "15",
    // badge: "ri-arrow-down-line",
    // badgeClass: "danger",
    // percentage: "2.52 %",
    // icon: "ri-checkbox-circle-line",
    // iconClass: "success",
    // decimals: 2,
    // prefix: "",
    // suffix: "K",
  },
  {
    id: 4,
    label: "Rejected",
    counter: "10",
    // badge: "ri-arrow-up-line",
    // badgeClass: "success",
    // percentage: "0.63 %",
    // icon: "ri-delete-bin-line",
    // iconClass: "danger",
    // decimals: 2,
    // prefix: "$",
    // suffix: "%",
  },
  {
    id: 5,
    label: "Approved",
    counter: "40",
    // badge: "ri-arrow-up-line",
    // badgeClass: "success",
    // percentage: "3.63 %",
    // icon: "ri-delete-bin-line",
    // iconClass: "danger",
    // decimals: 2,
    // prefix: "$",
    // suffix: "%",
  }
];

export { centersWidgets };
